spring.application.name=academic-platform

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${BD_URL}
spring.datasource.username=${BD_USERNAME}
spring.datasource.password=${BD_PASSWORD}

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-ms=${JWT_EXPIRATION}

spring.security.user.name=${SS_USER}
spring.security.user.password=${SS_PASSWORD}